version: '3.3'

services:
  app-composer:
      build: ./docker/php
      container_name: app_composer
      command: composer install
      volumes:
          - ./:/var/www/

  app-test:
      build: ./docker/php
      container_name: app_test
      command: ./vendor/bin/phpunit
      volumes:
          - ./:/var/www/

  app:
      build: ./docker/php
      container_name: app_searchmetrics
      command: php -S 0.0.0.0:8080 -t ./web/
      ports:
        - "8080:8080"
      volumes:
          - ./:/var/www/
