version: '3.3'

services:
  app-composer:
      build: ./docker/php
      container_name: app_composer
      command: composer install
      volumes:
          - ./:/var/www/

  app-test:
      build: ./docker/php
      container_name: app_test
      command: ./vendor/bin/phpunit
      volumes:
          - ./:/var/www/

  app:
      build: ./docker/php
      container_name: app_searchmetrics
      volumes:
          - ./:/var/www/
